environment:

  TOXENV: py
  TOX_TESTENV_PASSENV: DISTUTILS_USE_SDK MSSdk INCLUDE LIB
  # https://packaging.python.org/guides/supporting-windows-using-appveyor/#testing-with-tox

  matrix:

    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python

    - PYTHONDIR: "C:\\Python27-x64"
      JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/1.0/julia-1.0-latest-win64.exe"
    - PYTHONDIR: "C:\\Python36-x64"
      JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/1.0/julia-1.0-latest-win64.exe"

matrix:
  allow_failures:
    - PYTHONDIR: "C:\\Python27-x64"

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12"

# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile(
        $env:JULIA_URL,
        "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia
  - set PATH=C:\projects\julia\bin;%PATH%

# Install Python packages
  - "%PYTHONDIR%\\python.exe -m pip install --quiet tox"

build_script:
  # Empty so that it doesn't think it needs Visual Studio?
  - echo 'test'

test_script:
  - "SET PYTHON=%CD%\\.tox\\py\\scripts\\python.exe"
  - "%PYTHONDIR%\\scripts\\tox -- --cov diffeqpy"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
